language: cpp
compiler:
- gcc
os:
- linux
install:
- if [ $TRAVIS_OS_NAME == linux ]; then cd project2/bpt && make && cd -; fi
- if [ $TRAVIS_OS_NAME == linux ]; then cd project3/bpt && make && cd -; fi
- if [ $TRAVIS_OS_NAME == linux ]; then cd project4 && make && cd -; fi